### ISSUE TITLE
A biblioteca em src/library podemos deixa como required, nao precisamos versiona-la

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/senhaunica#1]

**Comment by masakik** [comment]
Tem no Packagist?

**Comment by thiagogomesverissimo** [comment]
qual o nome dessa biblioteca? se não existir, nós a registramos como read only.

**Comment by masakik** [comment]
esta é a biblioteca original
http://code.google.com/p/oauth-php/

**Comment by masakik** [comment]
https://packagist.org/packages/zorrodg/oauth-php
encontrei esta no packagist. Estou vendo ela

**Comment by masakik** [comment]
É a própria. Como é bom o mundo do software livre hehehe

**Comment by masakik** [comment]
Feito na versão 1.0
