### ISSUE TITLE
inserir no readme php-curl como dependência

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/senhaunica#4]

**Comment by alecostaweb** [comment]
Percebi isso quando fiz deploy do CoPaCo :smile:

**Comment by thiagogomesverissimo** [comment]
Sim, e eu percebi que faltava quando você abriu a issue lá :cat2:

**Comment by alecostaweb** [comment]
:+1:

**Comment by masakik** [comment]
coloquei como dependencia no composer também.
