### ISSUE TITLE
Só conecta na segunda tentativa

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/senhaunica#8]
@masakik , 

Não sei se você consegue reproduzir o erro, pois não consegui encontrar o padrão ainda, mas eventualmente é retornado "Error em obter access token" na primeira tentativa e na segunda vai de boas.

**Comment by thiagogomesverissimo** [comment]
Entendi o que ocorre. Na classe Senhaunica  as chaves temporárias são enviadas para  sessão (requests token). Isso está parcialmente correto, pois a biblioteca deveriam fazer as requisições oauth e não gerenciar sessão. O melhor é retornar as chaves temporárias e deixar que a sessão seja gerenciada pela aplicação (como fiz para o rails). Pois do jeito que está, não da para usar nenhum framework (eles tem jeitos próprios de gerenciar sessão) e mesmo que não seja esse o caso, ainda continua sendo um problema, pois interfere na regra de negócio de como a aplicação deve gerenciar a sessão.

**Comment by thiagogomesverissimo** [comment]
exemplo de alerta do symfony/drupal:

Applications should avoid using session_start(), session_regenerate_id(), session_id(), session_name(), and session_destroy() and instead use the APIs ...

**Comment by masakik** [comment]
Na biblioteca de oauth tem opção de session ou sql (mysql, pgsql, etc). Escolhendo session ele cria automaticamente a sessão.

**Comment by thiagogomesverissimo** [comment]
Eu trocaria a biblioteca de backend para https://github.com/thephpleague/oauth1-client
